function(enable_static_analysis project_name)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    
    option(ENABLE_CPPCHECK "Enable static analysis with cppcheck" OFF)
    option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" OFF)
    option(ENABLE_INCLUDE_WHAT_YOU_USE "Enable static analysis with include-what-you-use" OFF)

    if(ENABLE_CPPCHECK)
      find_program(CPPCHECK cppcheck)
      if(CPPCHECK)
        set(CMAKE_CXX_CPPCHECK ${CPPCHECK} --suppress=missingIncludeSystem)
      else()
        message(WARNING "cppcheck requested but executable not found")
      endif()
    endif()

    if(ENABLE_CLANG_TIDY)
      find_program(CLANGTIDY clang-tidy)
      if(CLANGTIDY)
        set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY} -extra-arg=-Wno-unknown-warning-option)
      else()
        message(WARNING "clang-tidy requested but executable not found")
      endif()
    endif()

    if(ENABLE_INCLUDE_WHAT_YOU_USE)
      find_program(IWYU include-what-you-use)
      if(IWYU)
        set(CMAKE_CXX_INCLUDE_WHAT_YOU_USE ${IWYU})
      else()
        message(WARNING "include-what-you-use requested but executable not found")
      endif()
    endif()

  endif()
endfunction()
